DROP TABLE "MEMBER" ;

CREATE TABLE "MEMBER"(
	EMAIL VARCHAR2(50) NOT NULL,
	NICKNAME VARCHAR2(30) NOT NULL,
	PASSWORD VARCHAR2(20),
	AUTH CHAR(1) NOT NULL,
	WITHDRAWAL CHAR(1) NOT NULL,
	JOINDATE DATE NOT NULL,
	CONSTRAINT "MEMBER_FK" CHECK ("AUTH" IN ('U','A')),
	CONSTRAINT "MEMBER_PK" PRIMARY KEY("EMAIL")
);


--회원가입을 하는 기능
INSERT INTO "MEMBER" 
(EMAIL,NICKNAME,PASSWORD,AUTH,WITHDRAWAL,JOINDATE)
VALUES('qr2277@naver.com','석규','tt001!','U','N',SYSDATE);

--API 회원가입 기능
INSERT INTO "MEMBER" 
(EMAIL, NICKNAME, AUTH, WITHDRAWAL, JOINDATE)
VALUES('josoekgyu@google.com','석규','U','N', SYSDATE);

--회원아이디중복체크 기능
SELECT COUNT(EMAIL) EMAIL
FROM MEMBER 
WHERE EMAIL = 'qr2277@naver.com';

--일반 회원 로그인 기능
SELECT EMAIL, NICKNAME, AUTH, JOINDATE
FROM MEMBER 
WHERE EMAIL = 'qr2277@naver.com'
AND PASSWORD = 'tt001!'
AND WITHDRAWAL = 'N';

--API 회원 로그인 기능
SELECT EMAIL,NICKNAME,AUTH,WITHDRAWAL
        FROM  MEMBER m 
        WHERE EMAIL ='josoekgyu@google.com'
        AND NICKNAME ='석규'
        AND WITHDRAWAL ='N';

       
CREATE TABLE MYMEMBER(
	EMAIL VARCHAR2(20) PRIMARY KEY,
	NICKNAME VARCHAR2(20)
);

INSERT INTO MYMEMBER(EMAIL, NICKNAME)
VALUES('A001', 'SUAN');


--NOTE 노트 테이블
CREATE TABLE NOTE(	
	NOTE_SEQ       NUMBER    PRIMARY KEY,
	EMAIL          VARCHAR2      (50),
	NOTE_DEL       CHAR      (1) DEFAULT 'N',
	NOTE_READCNT   NUMBER    ,
	NOTE_TITLE     VARCHAR2  (30) NOT NULL,
	NOTE_REGDATE   DATE
);

ALTER TABLE NOTE
ADD CONSTRAINT FK_EMAIL FOREIGN KEY(EMAIL) REFERENCES MYMEMBER(EMAIL);


--ONEDAY 하루 일정 테이블
CREATE TABLE ONEDAY(
	ONEDAY_SEQ NUMBER PRIMARY KEY,
	NOTE_SEQ NUMBER,
	ONEDAY_DELFLAG CHAR(1) DEFAULT 'N' NOT NULL,
	ONEDAY_TITLE VARCHAR2(30) NOT NULL,
	ONEDATE DATE NOT NULL,
	REPORTCHK     CHAR(1) DEFAULT 'N',
	ONE_READCNT   NUMBER,
	NOTE_PUBLIC CHAR(1) DEFAULT 'N'
);

ALTER TABLE ONEDAY
ADD CONSTRAINT FK_NOTE_SEQ FOREIGN KEY(NOTE_SEQ) REFERENCES NOTE(NOTE_SEQ);


-- PLACE 장소 테이블
CREATE TABLE PLACE (
	PLACE_SEQ NUMBER PRIMARY KEY,
	ONEDAY_SEQ NUMBER, --FK
	STEP NUMBER NOT NULL,
	PLACE_NAME VARCHAR2(50) NOT NULL,
	XLat DECIMAL(16,7) NOT NULL,
	YLNG DECIMAL(16,7) NOT NULL,
	MEMO VARCHAR2(4000)
);

ALTER TABLE PLACE 
ADD CONSTRAINT FK_ONEDAY_SEQ FOREIGN KEY(ONEDAY_SEQ) REFERENCES ONEDAY(ONEDAY_SEQ);


CREATE SEQUENCE SEQ_NOTE START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_ONEDAY START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_PLACE START WITH 1
INCREMENT BY 1;
       


--관리자 로그인 기능       
SELECT EMAIL, NICKNAME, PASSWORD AUTH, WITHDRAWAL , JOINDATE 
 FROM MEMBER m 
  WHERE EMAIL='CarpeDiem@gmail.com'
   AND PASSWORD ='ADMIN01'
   AND AUTH ='A';

--비밀번호 재설정 기능
UPDATE MEMBER SET PASSWORD ='tt0012!' 
WHERE EMAIL = 'qr2277@naver.com';


--회원탈퇴 기능
UPDATE MEMBER SET WITHDRAWAL ='Y'
WHERE EMAIL = 'qr2277@naver.com';

--전체 회원을 조회 하는 기능(페이징)
SELECT EMAIL,NICKNAME,AUTH,WITHDRAWAL,JOINDATE 
        FROM 
(SELECT EMAIL,NICKNAME,AUTH,WITHDRAWAL,JOINDATE, 
   ROW_NUMBER () OVER (ORDER BY JOINDATE DESC) ONE
        FROM MEMBER m)
WHERE ONE BETWEEN  1 AND 2 ;


-- 댓글 게시판 --
CREATE TABLE  COMMENTBOARD  (
	 COMM_SEQ 	NUMBER	NOT NULL,
	 ONEDAY_SEQ 	VARCHAR2(50)	NOT NULL,
	 EMAIL 	VARCHAR2(50)	NOT NULL,
	 REFFER 	NUMBER	NOT NULL,
	 DEPTH 	NUMBER	NOT NULL,
	 STEP 	NUMBER	NOT NULL,
	 REGDATE 	DATE	NOT NULL,
	 CONTENT 	VARCHAR2(500)	NOT NULL,
	 REPORTCHK 	CHAR(1) DEFAULT 'N' NOT NULL
);


-- 댓글 입력 -- 
INSERT INTO COMMENTBOARD(
	COMM_SEQ,ONEDAY_SEQ,
	EMAIL,REFFER,DEPTH,
	STEP,REGDATE,CONTENT)
	VALUES (SEQ_COMM.NEXTVAL,2,
	'A002',(SELECT NVL(MAX(REFFER),0) FROM COMMENTBOARD)+1,0,0,SYSDATE,'같이가욥');

-- 댓글 시퀀스 -- 
CREATE SEQUENCE SEQ_COMM START WITH 1
INCREMENT BY 1;

-- 답글 입력 --
-- 업데이트 먼저 --
UPDATE COMMENTBOARD SET STEP = STEP +1
	WHERE STEP > (SELECT STEP FROM COMMENTBOARD WHERE COMM_SEQ=2)
	AND REFFER = (SELECT REFFER FROM COMMENTBOARD WHERE COMM_SEQ=2);

-- 답글 작성 -- 
INSERT INTO COMMENTBOARD(
    COMM_SEQ,ONEDAY_SEQ,EMAIL,
    REFFER,DEPTH,
    STEP,REGDATE,CONTENT)
	VALUES(SEQ_COMM.NEXTVAL,2,'A004',
	(SELECT REFFER FROM COMMENTBOARD WHERE COMM_SEQ=2),(SELECT DEPTH FROM COMMENTBOARD WHERE COMM_SEQ = 2)+1,
	(SELECT STEP FROM COMMENTBOARD WHERE COMM_SEQ = 2)+1,SYSDATE,'너무 바쁘다');


-- 리뷰 게시판 --
CREATE TABLE  REVIEWBOARD  (
	PLACE_SEQ 	NUMBER	NOT NULL,
	UUID_NAME 	VARCHAR2(1000)	NULL,
	ORIGIN_NAME 	VARCHAR2(1000)	NULL,
	IMG_URL 	VARCHAR2(1000)	NULL,
	CONTENT 	VARCHAR2(1200)	NULL
);

ALTER TABLE REVIEWBOARD
ADD CONSTRAINT FK_PLACE_SEQ FOREIGN KEY(PLACE_SEQ) REFERENCES PLACE(PLACE_SEQ);
