SELECT * FROM CHATINGBOARD c ;

--로그인된 정보와 상대방 정보로 채팅방 생성
INSERT INTO CHATINGBOARD
(SEQ, CHATMYID, CHATYOURID, CHATGROUPID, CHATCONTENT, CHATREGDATE,CHATDELFLAG)
VALUES(CHATINGBOARD_SEQ.NEXTVAL,'우성(sung960607@gmail.com)','우성1(sung9606071@naver.com)','우성(sung960607@gmail.com),우성1(sung9606071@naver.com)','',SYSDATE,'N');

--생성된내역이 있다면 대화내역 가져오기
SELECT SEQ, CHATMYID, CHATYOURID,CHATCONTENT FROM CHATINGBOARD c 
WHERE CHATMYID ='우성1(sung9606071@naver.com)'
AND CHATYOURID ='우성(sung960607@gmail.com)';

UPDATE CHATINGBOARD SET CHATREGDATE =SYSDATE 
WHERE CHATMYID ='우성1(sung9606071@naver.com)'
AND CHATYOURID = '우성(sung960607@gmail.com';

--채팅방을 생성한 본인이 채팅방 삭제 버튼 클릭시 채팅방 삭제
DELETE FROM CHATINGBOARD c
WHERE CHATMYID ='우성1(sung9606071@naver.com)'
AND SEQ ='1';

--회원이 입력한 메세지를 DB에 저장
UPDATE CHATINGBOARD SET CHATCONTENT ='대화내용이 들어갑니다.',CHATREGDATE =SYSDATE 
WHERE CHATMYID ='우성1(sung9606071@naver.com)'
AND CHATYOURID = '우성(sung960607@gmail.com';


--채팅방 최근현황 10개 조회
SELECT CHATGROUPID,CHATMYID FROM
(SELECT CHATGROUPID,CHATMYID ,ROW_NUMBER () OVER(ORDER BY CHATREGDATE DESC) RN
FROM CHATINGBOARD c
WHERE CHATDELFLAG ='N'
AND CHATMYID ='우성1(sung9606071@naver.com)')
WHERE RN BETWEEN 1 AND 10;
