DROP TABLE "MEMBER" ;



-- 1.여행 회원 만들기
CREATE TABLE "MEMBER" (
	EMAIL VARCHAR2(50) NOT NULL, --회원 아이디
	NICKNAME VARCHAR2(30) NOT NULL, -- 닉네임
	PASSWORD VARCHAR2(20), --비밀번호
	AUTH CHAR(1) NOT NULL, -- 권한
	WITHDRAWAL CHAR(1) NOT NULL, -- 탈퇴여부
	JOINDATE DATE NOT NULL, -- 가입일
	CONSTRAINT "MEMBER_CK" CHECK ("AUTH" IN ('U','A')),
	CONSTRAINT "MEMBER_PK" PRIMARY KEY("EMAIL")
);

-- 2. 회원 가입
INSERT INTO "MEMBER" 
(EMAIL,NICKNAME,PASSWORD,AUTH,WITHDRAWAL,JOINDATE)
VALUES('joseokgyu@naver.com','벤쿠버불곰','qnfrha12@','U','N',SYSDATE);

-- 3. API회원 가입
INSERT INTO "MEMBER" 
(EMAIL, NICKNAME, AUTH, WITHDRAWAL, JOINDATE)
VALUES('josoekgyu12@google.com','석규','U','N', SYSDATE);

-- 관리자 회원가입
INSERT INTO "MEMBER" 
(EMAIL,NICKNAME,PASSWORD,AUTH,WITHDRAWAL,JOINDATE)
VALUES('CarpeDiem@gmail.com','운영자','ADMIN01','A','N',SYSDATE);



-- 4. 회원 아이디 중복 체크
SELECT COUNT(EMAIL) EMAIL
FROM "MEMBER" 
WHERE EMAIL = 'josoekgyu12@google.com';

-- 5. 일반 회원 로그인
SELECT EMAIL, NICKNAME, AUTH, JOINDATE
FROM "MEMBER" 
WHERE EMAIL = 'joseokgyu@naver.com'
AND PASSWORD = 'qnfrha12@'
AND WITHDRAWAL = 'N';

-- 6. API 회원 로그인
SELECT EMAIL,NICKNAME,AUTH,WITHDRAWAL
        FROM  "MEMBER" m 
        WHERE EMAIL ='josoekgyu12@google.com'
        AND NICKNAME ='석규'
        AND WITHDRAWAL ='N'; 
       
-- 7. 관리자 로그인
SELECT EMAIL, NICKNAME, PASSWORD AUTH, WITHDRAWAL , JOINDATE 
 FROM "MEMBER" m 
  WHERE EMAIL='CarpeDiem@gmail.com'
   AND PASSWORD ='ADMIN01'
   AND AUTH ='A';
  
-- 8. 비밀번호 재설정
UPDATE "MEMBER" SET PASSWORD ='qnfrha12@' 
WHERE EMAIL = 'joseokgyu@naver.com';

-- 9. 회원탈퇴
UPDATE "MEMBER" SET WITHDRAWAL ='Y'
WHERE EMAIL = 'qr2277@naver.com';

-- 회원전체조회 (페이징)
SELECT EMAIL,NICKNAME,AUTH,WITHDRAWAL,JOINDATE 
        FROM 
(SELECT EMAIL,NICKNAME,AUTH,WITHDRAWAL,JOINDATE, 
                                ROW_NUMBER () OVER (ORDER BY AUTH DESC) ONE
        FROM "MEMBER" m)
WHERE ONE BETWEEN  1 AND 10 ; 

SELECT EMAIL ,NICKNAME ,PASSWORD ,AUTH ,WITHDRAWAL ,JOINDATE 
	FROM "MEMBER" m 

