
CREATE TABLE "MEMBER"  (
	 EMAIL 	VARCHAR2(50)	NOT NULL PRIMARY KEY,
	 PASSWORD 	VARCHAR2(20) NOT NULL,
	 WITHDRAWAL 	CHAR(1)	 DEFAULT 'Y'NOT NULL,
	 JOINDATE 	DATE	NOT NULL,
	 NICKNAME 	VARCHAR2(30)	NOT NULL,
	 AUTH 	CHAR(1)		DEFAULT 'U' NOT NULL
);

DROP TABLE "MEMBER" ;

ALTER TABLE NOTE
ADD CONSTRAINT FK_EMAIL FOREIGN KEY(EMAIL) REFERENCES "MEMBER"(EMAIL);

ALTER TABLE NOTE
ADD CONSTRAINT FK_EMAIL FOREIGN KEY(EMAIL)
REFERENCES "MEMBER"(EMAIL);




