SELECT p.ONEDAY_SEQ, p.PLACE_SEQ, p.STEP, p.PLACE_NAME, p.XLAT, p.YLNG, p.MEMO
FROM  PLACE p
WHERE p.ONEDAY_SEQ=72 AND p.PLACE_SEQ=56
ORDER BY STEP ASC;

SELECT p.ONEDAY_SEQ, p.PLACE_SEQ, p.STEP, p.PLACE_NAME, p.XLAT, p.YLNG, p.MEMO
FROM  PLACE p
WHERE p.PLACE_SEQ=72
ORDER BY STEP ASC;

SELECT p.ONEDAY_SEQ, p.PLACE_SEQ, p.STEP, p.PLACE_NAME, p.XLAT, p.YLNG, p.MEMO
FROM  PLACE p
WHERE p.ONEDAY_SEQ=56 AND p.STEP = 1
ORDER BY STEP ASC;

SELECT NOTE_TITLE
FROM NOTE
WHERE NOTE_SEQ = '1';

SELECT ONEDAY_TITLE , ONEDATE 
FROM ONEDAY
WHERE ONEDAY_SEQ = '1';