
DROP TABLE NOTE;
DROP TABLE ONEDAY; 
DROP TABLE PLACE;
DROP TABLE MYMEMBER;

CREATE TABLE MYMEMBER(
	EMAIL VARCHAR2(20) PRIMARY KEY,
	NICKNAME VARCHAR2(20)
);

INSERT INTO MYMEMBER(EMAIL, NICKNAME)
VALUES('A001', 'SUAN');

--NOTE 노트 테이블
CREATE TABLE NOTE(	
	NOTE_SEQ       NUMBER    PRIMARY KEY,
	EMAIL          VARCHAR2      (50),
	NOTE_DEL       CHAR      (1) DEFAULT 'N',
	NOTE_READCNT   NUMBER    ,
	NOTE_TITLE     VARCHAR2  (30) NOT NULL,
	NOTE_REGDATE   DATE
);

ALTER TABLE NOTE
ADD CONSTRAINT FK_EMAIL FOREIGN KEY(EMAIL) REFERENCES MYMEMBER(EMAIL);


--ONEDAY 하루 일정 테이블
CREATE TABLE ONEDAY(
	ONEDAY_SEQ NUMBER PRIMARY KEY,
	NOTE_SEQ NUMBER,
	ONEDAY_DELFLAG CHAR(1) DEFAULT 'N' NOT NULL,
	ONEDAY_TITLE VARCHAR2(30) NOT NULL,
	ONEDATE DATE NOT NULL,
	REPORTCHK     CHAR(1) DEFAULT 'N',
	ONE_READCNT   NUMBER,
	NOTE_PUBLIC CHAR(1) DEFAULT 'N'
);


ALTER TABLE ONEDAY
ADD CONSTRAINT FK_NOTE_SEQ FOREIGN KEY(NOTE_SEQ) REFERENCES NOTE(NOTE_SEQ);

-- PLACE 장소 테이블
CREATE TABLE PLACE (
	PLACE_SEQ NUMBER PRIMARY KEY,
	ONEDAY_SEQ NUMBER, --FK
	STEP NUMBER NOT NULL,
	PLACE_NAME VARCHAR2(50) NOT NULL,
	XLat DECIMAL(16,7) NOT NULL,
	YLNG DECIMAL(16,7) NOT NULL,
	MEMO VARCHAR2(4000)
);

ALTER TABLE PLACE 
ADD CONSTRAINT FK_ONEDAY_SEQ FOREIGN KEY(ONEDAY_SEQ) REFERENCES ONEDAY(ONEDAY_SEQ);
--ALTER TABLE PLACE
--ADD CONSTRAINT PFK_EMAIL FOREIGN KEY(EMAIL) REFERENCES MYMEMBER(EMAIL);


ALTER TABLE NOTE
ADD CONSTRAINT FK_EMAIL FOREIGN KEY(EMAIL) REFERENCES MYMEMBER(EMAIL);
ALTER TABLE ONEDAY
ADD CONSTRAINT FK_NOTE_SEQ FOREIGN KEY(NOTE_SEQ) REFERENCES NOTE(NOTE_SEQ);
ALTER TABLE PLACE 
ADD CONSTRAINT FK_ONEDAY_SEQ FOREIGN KEY(ONEDAY_SEQ) REFERENCES ONEDAY(ONEDAY_SEQ);

CREATE SEQUENCE SEQ_NOTE START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_ONEDAY START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_PLACE START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE PLACE_STEP START WITH 1
INCREMENT BY 1;

DROP SEQUENCE SEQ_NOTE;
DROP SEQUENCE SEQ_ONEDAY;
DROP SEQUENCE SEQ_PLACE;
DROP SEQUENCE PLACE_STEP;
-- 쿼리테스트

	-- 노트 --
--노트를 전체 조회하는 기능

-- 내노트 조회
SELECT NOTE_SEQ, NOTE_TITLE
FROM NOTE
WHERE EMAIL = 'A001' AND NOTE_DEL = 'N';



--노트를 생성하는 기능
INSERT INTO NOTE
(NOTE_SEQ, EMAIL, NOTE_DEL, NOTE_READCNT, NOTE_TITLE, NOTE_REGDATE)
VALUES(SEQ_NOTE.NEXTVAL, 'A001', 'N', 0, '제주도여행', SYSDATE);



--노트 제목을 수정하는 기능
UPDATE NOTE
SET NOTE_TITLE='신나는 제주도 여행'
WHERE NOTE_SEQ=1 AND EMAIL='A001';

--노트를 삭제하는 기능
UPDATE NOTE
SET  NOTE_DEL='Y'
WHERE NOTE_SEQ=1;

-- 노트 다중삭제
UPDATE NOTE
SET  NOTE_DEL='Y'
WHERE NOTE_SEQ IN(1,2,3);


--노트를 상세조회 하는 기능
SELECT NOTE_SEQ, EMAIL, NOTE_TITLE
FROM NOTE JO
WHERE NOTE_SEQ = 1 AND NOTE_DEL = 'N';

-- 노트 상세조회 (해당하는 내 노트의 모든 하루일정 조회)
SELECT n.NOTE_SEQ, n.NOTE_TITLE , n.EMAIL, o.ONEDAY_TITLE, o.ONEDAY_SEQ , o.ONEDATE, o.ONEDAY_DELFLAG 
FROM NOTE n JOIN ONEDAY o
ON n.NOTE_SEQ = o.NOTE_SEQ
WHERE n.NOTE_SEQ = 61 AND o.ONEDAY_DELFLAG = 'N';

-- JOIN
	-- 하루 일정 --
--하루 일정을 전체 조회하는 기능
--SELECT ONEDAY_SEQ, NOTE_SEQ, ONEDAY_TITLE, ONEDATE
--FROM ONEDAY
--WHERE EMAIL='A001' AND ONEDAY_DELFLAG = 'N';

--하루 일정을 생성하는 기능
INSERT INTO ONEDAY
(ONEDAY_SEQ, NOTE_SEQ, ONEDAY_DELFLAG, ONEDAY_TITLE, ONEDATE, REPORTCHK, ONE_READCNT, NOTE_PUBLIC)
VALUES(SEQ_ONEDAY.NEXTVAL, 61, 'N' , '제주도2일차', '20200102', 'N', 0, 'N'
);


	
--하루 일정의 제목과 날짜 수정
UPDATE ONEDAY
SET ONEDAY_TITLE='제주도 여행 1일차', ONEDATE='20201230'
WHERE ONEDAY_SEQ= 1 ;

--하루 일정을 삭제
UPDATE ONEDAY
SET ONEDAY_DELFLAG ='Y'
WHERE ONEDAY_SEQ= 1 AND EMAIL = 'A001';

--하루 일정을 상세조회
SELECT ONEDAY_SEQ, NOTE_SEQ, EMAIL, ONEDAY_TITLE, ONEDATE
FROM ONEDAY
WHERE ONEDAY_SEQ = 1;

-- 장소 --
SELECT ONEDAY_SEQ, NOTE_SEQ, EMAIL, ONEDAY_TITLE, ONEDATE
FROM ONEDAY
WHERE ONEDAY_SEQ = 1;

--해당하는 하루 일정의 모든 장소 조회
SELECT p.ONEDAY_SEQ,  p.STEP, p.PLACE_NAME, p.XLAT, p.YLNG, p.MEMO
FROM ONEDAY o JOIN PLACE p
ON o.ONEDAY_SEQ = p.ONEDAY_SEQ
WHERE o.EMAIL='A001'
ORDER BY STEP ASC;


--장소를 생성(추가)하는 기능

INSERT INTO PLACE
(PLACE_SEQ, ONEDAY_SEQ, STEP, PLACE_NAME, XLAT, YLNG, MEMO)
VALUES(SEQ_ONEDAY.NEXTVAL, 47, 3, '제주도', 33.3658656, 126.5422809, '');
VALUES(SEQ_ONEDAY.NEXTVAL, 47, 2, '올레길', 33.3658656, 126.5422809, '');
VALUES(SEQ_ONEDAY.NEXTVAL, 1, 3, '올레길', 33.3658656, 126.5422809, '');

-- 장소를 순서를 수정하는 기능

-- 요구사항 추가
-- 한개만 있으면 위아래 버튼이 없어야함.
	-- 버튼 위로 클릭
	-- 맨위에 장소는 위 버튼 없어야함
UPDATE PLACE
SET STEP = STEP-1
WHERE PLACE_SEQ = 3 AND ONEDAY_SEQ = 1;
--트랜잭션
UPDATE PLACE
SET STEP = STEP+1
WHERE PLACE_SEQ = 2 AND ONEDAY_SEQ = 1;
	-- 버튼 아래 클릭
	-- 맨아래 장소는 아래 버튼이 없어야함
UPDATE PLACE
SET STEP = STEP+1
WHERE PLACE_SEQ = 3 AND ONEDAY_SEQ = 1;

UPDATE PLACE 
SET STEP = STEP-1
WHERE PLACE_SEQ = 2 AND ONEDAY_SEQ = 1;

--장소를 삭제하는 기능
DELETE FROM PLACE
WHERE PLACE_SEQ=1 AND EMAIL = 'A001';

-- 위에 있는 장소가 삭제 했을 때 스탭을 바꿔 주어야함
UPDATE PLACE
SET STEP = STEP-1
WHERE STEP > (SELECT STEP FROM PLACE WHERE PLACE_SEQ=2);

--메모를 생성(추가)하는 기능
UPDATE PLACE
SET MEMO='메모를 추가합니다'
WHERE PLACE_SEQ=2;

SELECT PLACE_SEQ, PLACE_NAME 
FROM PLACE p 
WHERE PLACE_NAME = '한라산국립공원';

SELECT o.ONEDAY_SEQ, p.ONEDAY_SEQ,  p.ONEDAY_SEQ, p.STEP, p.PLACE_NAME, p.XLAT, p.YLNG, p.MEMO
FROM ONEDAY o JOIN PLACE p
ON o.ONEDAY_SEQ = p.ONEDAY_SEQ
WHERE o.ONEDAY_SEQ=1
ORDER BY STEP ASC;

ALTER TABLE NOTE
ADD CONSTRAINT FK_EMAIL FOREIGN KEY(EMAIL) REFERENCES MYMEMBER(EMAIL);
ALTER TABLE ONEDAY
ADD CONSTRAINT FK_NOTE_SEQ FOREIGN KEY(NOTE_SEQ) REFERENCES NOTE(NOTE_SEQ);
ALTER TABLE PLACE 
ADD CONSTRAINT FK_ONEDAY_SEQ FOREIGN KEY(ONEDAY_SEQ) REFERENCES ONEDAY(ONEDAY_SEQ);

CREATE SEQUENCE SEQ_NOTE START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_ONEDAY START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_PLACE START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE PLACE_STEP START WITH 1
INCREMENT BY 1;


	
		SELECT o.ONEDAY_SEQ, o.ONEDAY_TITLE, o.ONEDATE,
		p.ONEDAY_SEQ, p.PLACE_SEQ, p.STEP, p.PLACE_NAME,
		p.XLAT, p.YLNG,
		p.MEMO
		FROM ONEDAY o JOIN PLACE p
		ON o.ONEDAY_SEQ = p.ONEDAY_SEQ
		WHERE o.ONEDAY_SEQ= 47
		ORDER BY STEP ASC;
		
		