CREATE TABLE "MEMBER"  (
	 EMAIL 	VARCHAR2(50)	NOT NULL PRIMARY KEY,
	 PASSWORD 	VARCHAR2(20) NOT NULL,
	 WITHDRAWAL 	CHAR(1)	 DEFAULT 'Y'NOT NULL,
	 JOINDATE 	DATE	NOT NULL,
	 NICKNAME 	VARCHAR2(30)	NOT NULL,
	 AUTH 	CHAR(1)		DEFAULT 'U' NOT NULL
);

-- 댓글 게시판 --

CREATE TABLE  COMMENTBOARD  (
	 COMM_SEQ 	NUMBER	NOT NULL PRIMARY KEY,
	 ONEDAY_SEQ NUMBER	NOT NULL,
	 EMAIL 	VARCHAR2(50)	NOT NULL,
	 REFFER 	NUMBER	NOT NULL,
	 DEPTH 	NUMBER	NOT NULL,
	 STEP 	NUMBER	NOT NULL,
	 REGDATE 	DATE	NOT NULL,
	 CONTENT 	VARCHAR2(500)	NOT NULL,
	 REPORTCHK 	CHAR(1) DEFAULT 'N' NOT NULL
);

DROP TABLE COMMENTBOARD;

-- 댓글 시퀀스 -- 
CREATE SEQUENCE SEQ_COMM START WITH 1
INCREMENT BY 1;

ALTER TABLE COMMENTBOARD
ADD CONSTRAINT ONEDAY_SEQ_FK FOREIGN KEY(ONEDAY_SEQ) REFERENCES ONEDAY(ONEDAY_SEQ);



-- 댓글 입력 -- 
INSERT INTO COMMENTBOARD(
	COMM_SEQ,ONEDAY_SEQ,
	EMAIL,REFFER,DEPTH,
	STEP,REGDATE,CONTENT)
	VALUES (SEQ_COMM.NEXTVAL,2,
	'A002',(SELECT NVL(MAX(REFFER),0) FROM COMMENTBOARD)+1,0,0,SYSDATE,'같이가욥');


-- 댓글 삭제 --
DELETE FROM COMMENTBOARD
WHERE ONEDAY_SEQ = 2 
AND REFFER = 5 AND STEP >= 0;

-- 업데이트 먼저 --
UPDATE COMMENTBOARD SET STEP = STEP +1
	WHERE STEP > (SELECT STEP FROM COMMENTBOARD WHERE COMM_SEQ=2)
	AND REFFER = (SELECT REFFER FROM COMMENTBOARD WHERE COMM_SEQ=2);

-- 답글 작성 -- 
INSERT INTO COMMENTBOARD(
    COMM_SEQ,ONEDAY_SEQ,EMAIL,
    REFFER,DEPTH,
    STEP,REGDATE,CONTENT)
	VALUES(SEQ_COMM.NEXTVAL,2,'A004',
	(SELECT REFFER FROM COMMENTBOARD WHERE COMM_SEQ=2),(SELECT DEPTH FROM COMMENTBOARD WHERE COMM_SEQ = 2)+1,
	(SELECT STEP FROM COMMENTBOARD WHERE COMM_SEQ = 2)+1,SYSDATE,'너무 바쁘다');


-- 리뷰 게시판 --
CREATE TABLE  REVIEWBOARD  (
	PLACE_SEQ 	NUMBER	NOT NULL,
	UUID_NAME 	VARCHAR2(1000)	NULL,
	ORIGIN_NAME 	VARCHAR2(1000)	NULL,
	IMG_URL 	VARCHAR2(1000)	NULL,
	CONTENT 	VARCHAR2(1200)	NULL
);

ALTER TABLE REVIEWBOARD
ADD CONSTRAINT FK_PLACE_SEQ FOREIGN KEY(PLACE_SEQ) REFERENCES PLACE(PLACE_SEQ);

-- 후기 조회 게시판 페이징 

SELECT ONEDAY_SEQ, NOTE_SEQ, ONEDAY_DELFLAG, ONEDAY_TITLE, ONEDATE, REPORTCHK, ONE_READCNT, ONEDAY_PUBLIC
	FROM (SELECT ROW_NUMBER () OVER (ORDER BY ONEDATE DESC) RN,
	ONEDAY_SEQ, NOTE_SEQ, ONEDAY_DELFLAG, ONEDAY_TITLE, ONEDATE, REPORTCHK, ONE_READCNT, ONEDAY_PUBLIC
			FROM TRIP.ONEDAY
			WHERE ONEDAY_DELFLAG = 'N' AND ONEDAY_PUBLIC = 'Y')
	WHERE RN BETWEEN 01 AND 5


-- 페이징 셀렉트 
	
	SELECT ONEDAY_SEQ, NOTE_SEQ, ONEDAY_DELFLAG, ONEDAY_TITLE, ONEDATE, REPORTCHK, ONE_READCNT, ONEDAY_PUBLIC, EMAIL
	FROM (SELECT ROW_NUMBER () OVER (ORDER BY ONEDATE DESC) RN,
	ONEDAY_SEQ, o.NOTE_SEQ, ONEDAY_DELFLAG, ONEDAY_TITLE, ONEDATE, REPORTCHK, ONE_READCNT, ONEDAY_PUBLIC,EMAIL
			FROM ONEDAY o JOIN NOTE n 
			ON o.NOTE_SEQ = n.NOTE_SEQ
			WHERE ONEDAY_DELFLAG = 'N' AND ONEDAY_PUBLIC = 'Y')
	WHERE RN BETWEEN 1 AND 5;

-- 조회수 

	UPDATE TRIP.ONEDAY SET ONE_READCNT=ONE_READCNT+1 
	 WHERE ONEDAY_SEQ=51;

	UPDATE TRIP.ONEDAY SET ONE_READCNT=ONE_READCNT+1
		WHERE ONEDAY_SEQ=51;
		
	
UPDATE PLACE
	SET STEP = STEP-1
	WHERE STEP > (SELECT STEP FROM PLACE WHERE PLACE_SEQ=2)
	
	
DELETE FROM COMMENTBOARD
	WHERE ONEDAY_SEQ = 1
	AND REFFER = 1 AND STEP > 1;	
	

DELETE FROM COMMENTBOARD
	WHERE ONEDAY_SEQ = 1
	AND REFFER = 1 
	AND STEP > (SELECT STEP FROM COMMENTBOARD WHERE COMM_SEQ=5);