DROP TABLE MEMBERBOARD ;
DROP TABLE TRIPSEARCHBOARD ;
DROP TABLE CHATINGBOARD ;
DROP TABLE REPORTBOARD ;

CREATE TABLE MEMBERBOARD(
USERSEQ NUMBER,
NICKNAME VARCHAR2(50) NOT NULL,
USERID VARCHAR2(40) NOT NULL,
AUTH VARCHAR2(5) NOT NULL, 
CONSTRAINT MEMBERBOARD_PK PRIMARY KEY (USERID)
);




CREATE SEQUENCE MEMBERBOARD_SEQ MINVALUE 1 MAXVALUE 9999 INCREMENT BY 1 START WITH 1 ;

CREATE TABLE TRIPSEARCHBOARD(
SEQ 		NUMBER NOT NULL,
USERID  	VARCHAR2(50) NOT NULL, 
NICKNAME    VARCHAR2(50) NOT NULL,
BOARDTITLE  VARCHAR2(100) NOT NULL,
DELFLAG     CHAR(1) NOT NULL,
TRIPREGDATE DATE NOT NULL,
REPORT_STATUS CHAR(1) NOT NULL,
CONSTRAINT TRIPSEARCHBOARD_PK PRIMARY KEY (SEQ),
CONSTRAINT TRIPSEARCHBOARD_FK FOREIGN KEY (USERID) REFERENCES MEMBERBOARD(USERID)
);



CREATE SEQUENCE TRIPSEARCHBOARD_SEQ MINVALUE 1 MAXVALUE 9999 INCREMENT BY 1 START WITH 1 ;

CREATE TABLE CHATINGBOARD(
SEQ            		NUMBER   NOT NULL,
CHATMYID      VARCHAR2(50)  NOT NULL,
CHATYOURID	   		VARCHAR2(50) NOT NULL,
CHATGROUPID			VARCHAR2(100) NOT NULL,
CHATCONTENT    		VARCHAR2(4000),
CHATREGDATE    		DATE  NOT NULL,
REPORT_STATUS		CHAR(1) 	NOT NULL,
CONSTRAINT CHATINGBOARD_PK PRIMARY KEY (SEQ)
);

CREATE SEQUENCE CHATINGBOARD_SEQ MINVALUE 1 MAXVALUE 9999 INCREMENT BY 1 START WITH 1 ;

-- 신고처리 게시판
CREATE TABLE REPORTBOARD (
	SEQ NUMBER NOT NULL,
	EMAIL VARCHAR2(30) NOT NULL,
	NICKNAME VARCHAR2(10) NOT NULL,
	REPORT_TYPE VARCHAR2(50) NOT NULL,
	BOARD_TYPE VARCHAR2(50) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	TEXT_REGDATE DATE NOT NULL,
	WITHDRAWAL CHAR(1) NOT NULL,
	PROCESSING_STATUS CHAR(1) NOT NULL,
	CONSTRAINT "REPORTBOARD_PK" PRIMARY KEY("SEQ"),
	CONSTRAINT "REPORTBOARD_FK" FOREIGN KEY("EMAIL") REFERENCES MEMBERBOARD("USERID")
);

CREATE SEQUENCE REPORTBOARD_SEQ START WITH 1 INCREMENT BY 1;

--MEMBER TEST로 넣기
INSERT INTO MEMBERBOARD
(USERSEQ, NICKNAME, USERID,AUTH)
VALUES(MEMBERBOARD_SEQ.NEXTVAL, '우성1', 'sung9606071@gmail.com','USER');

INSERT INTO MEMBERBOARD
(USERSEQ, NICKNAME, USERID,AUTH)
VALUES(MEMBERBOARD_SEQ.NEXTVAL, '최우성', 'dntjd0123@naver.com','ADMIN');

INSERT INTO MEMBERBOARD
(USERSEQ, NICKNAME, USERID,AUTH)
VALUES(MEMBERBOARD_SEQ.NEXTVAL, '우성', 'happy0401@gmail.com','USER');


SELECT * FROM MEMBERBOARD m ;

-------MEMBERBOARD------------------------

SELECT * FROM TRIPSEARCHBOARD t2 ;
-- 글 제목 입력
INSERT INTO TRIPSEARCHBOARD(SEQ,USERID,NICKNAME,
BOARDTITLE,DELFLAG,TRIPREGDATE,REPORT_STATUS) 
VALUES(TRIPSEARCHBOARD_SEQ.NEXTVAL,'dntjd0123@naver.com','최우성',
'저랑 같이 제주도 가실분 구합니다.','N',SYSDATE,'N');

--동행 게시판 
--전체 조회(관리자) 페이징
SELECT SEQ ,USERID ,NICKNAME,
BOARDTITLE ,DELFLAG ,TRIPREGDATE,REPORT_STATUS
FROM(SELECT SEQ ,USERID ,NICKNAME,
BOARDTITLE ,DELFLAG ,TRIPREGDATE,REPORT_STATUS,ROW_NUMBER () OVER(ORDER BY TRIPREGDATE DESC) RN
FROM TRIPSEARCHBOARD t
WHERE REPORT_STATUS ='N')
WHERE RN BETWEEN 1 AND 10 ;

--동행 게시판 
--삭제된 글을 제외한 젠체조회(회원)
SELECT SEQ ,USERID ,NICKNAME,
BOARDTITLE ,DELFLAG ,TRIPREGDATE,REPORT_STATUS
FROM (SELECT SEQ ,USERID ,NICKNAME,
BOARDTITLE ,DELFLAG ,TRIPREGDATE,REPORT_STATUS,ROW_NUMBER () OVER(ORDER BY TRIPREGDATE DESC) RN
FROM TRIPSEARCHBOARD t) 
WHERE DELFLAG ='N'
AND REPORT_STATUS ='N'
AND RN BETWEEN 1 AND 10;

--개인글 삭제, 다중삭제, 관리자 삭제

-- 개인 글 삭제,다중삭제
UPDATE TRIPSEARCHBOARD SET DELFLAG ='Y'
WHERE USERID = 'sung9606071@gmail.com'
AND SEQ='2';

--관리자 삭제
UPDATE TRIPSEARCHBOARD SET DELFLAG ='Y'
WHERE SEQ = '2'
AND AUTH ='ADMIN';

-----------------TRIPSEARCHBOARD -------------------

SELECT * FROM REPORTBOARD;

INSERT INTO REPORTBOARD
(SEQ, EMAIL, NICKNAME, 
REPORT_TYPE,BOARD_TYPE, CONTENT, TEXT_REGDATE,
WITHDRAWAL, PROCESSING_STATUS)
VALUES(REPORTBOARD_SEQ.NEXTVAL,'sung9606071@gmail.com', '우성',
'욕설/비방','tripboard'||'2','', '',
'', '');

UPDATE CHATINGBOARD SET CHATREGDATE =ACCESSMEMBER='Y'
WHERE GROUPID ='우성1(sung9606071@naver.com),우성(sung960607@gmail.com)'


-----------------REPORTBOARD -----------------------

-- 채팅방 확인하기 위해서 그냥 씀
SELECT * FROM CHATINGBOARD c 
ORDER BY CHATREGDATE DESC;

-- 로그인된 정보와 상대방 정보로 채팅방 생성

INSERT INTO CHATINGBOARD
(SEQ, CHATMYID, CHATYOURID, CHATGROUPID, CHATCONTENT, CHATREGDATE,REPORT_STATUS)
VALUES(CHATINGBOARD_SEQ.NEXTVAL,'우성1(sung9606071@naver.com)','test(happy0104@gmail.com)',
'우성1(sung9606071@naver.com),test(happy0104@gmail.com)',NULL,SYSDATE,'N');

-- 채팅방 시간 업데이트
UPDATE CHATINGBOARD SET CHATREGDATE =SYSDATE 
WHERE CHATMYID ='우성1(sung9606071@naver.com)';

-- 채팅방이 생성정보가 있을경우 대화내용 가져오기
UPDATE CHATINGBOARD SET CHATREGDATE =SYSDATE 
WHERE CHATMYID ='우성1(sung9606071@naver.com)'
AND CHATYOURID ='우성(sung960607@gmail.com)';

-- 회원이 입력한 메세지를 DB에 저장
SELECT CHATMYID ,CHATYOURID ,CHATCONTENT FROM CHATINGBOARD c 
WHERE CHATMYID ='우성1(sung9606071@naver.com)'
AND CHATYOURID ='우성(sung960607@gmail.com)';

--채팅방 최근현황 10개 조회
SELECT CHATGROUPID,CHATMYID FROM
(SELECT CHATGROUPID,CHATMYID ,ROW_NUMBER () OVER(ORDER BY CHATREGDATE DESC) RN
FROM CHATINGBOARD c
WHERE CHATDELFLAG ='N')
WHERE RN BETWEEN 1 AND 10
AND CHATMYID ='우성1(sung9606071@naver.com)';

-- 채팅 삭제
DELETE FROM CHATINGBOARD c
WHERE CHATMYID ='우성1(sung9606071@naver.com)'
AND CHATGROUPID = '우성1(sung9606071@naver.com),우성(sung960607@gmail.com)';













SELECT * FROM CHATINGBOARD c ;

--로그인된 정보와 상대방 정보로 채팅방 생성
INSERT INTO CHATINGBOARD
(SEQ, CHATMYID, CHATYOURID, CHATGROUPID, CHATCONTENT, CHATREGDATE,CHATDELFLAG)
VALUES(CHATINGBOARD_SEQ.NEXTVAL,'우성(sung960607@gmail.com)','우성1(sung9606071@naver.com)','우성(sung960607@gmail.com),우성1(sung9606071@naver.com)','',SYSDATE,'N');

--생성된내역이 있다면 대화내역 가져오기
SELECT SEQ, CHATMYID, CHATYOURID,CHATCONTENT FROM CHATINGBOARD c 
WHERE CHATMYID ='우성1(sung9606071@naver.com)'
AND CHATYOURID ='우성(sung960607@gmail.com)';

UPDATE CHATINGBOARD SET CHATREGDATE =SYSDATE 
WHERE CHATMYID ='우성1(sung9606071@naver.com)'
AND CHATYOURID = '우성(sung960607@gmail.com';

--채팅방을 생성한 본인이 채팅방 삭제 버튼 클릭시 채팅방 삭제
DELETE FROM CHATINGBOARD c
WHERE CHATMYID ='우성1(sung9606071@naver.com)'
AND SEQ ='1';

--회원이 입력한 메세지를 DB에 저장
UPDATE CHATINGBOARD SET CHATCONTENT ='대화내용이 들어갑니다.',CHATREGDATE =SYSDATE 
WHERE CHATMYID ='우성1(sung9606071@naver.com)'
AND CHATYOURID = '우성(sung960607@gmail.com';


--채팅방 최근현황 10개 조회
SELECT CHATGROUPID,CHATMYID FROM
(SELECT CHATGROUPID,CHATMYID ,ROW_NUMBER () OVER(ORDER BY CHATREGDATE DESC) RN
FROM CHATINGBOARD c
WHERE CHATDELFLAG ='N'
AND CHATMYID ='우성1(sung9606071@naver.com)')
WHERE RN BETWEEN 1 AND 10;
