SELECT SEQ, EMAIL, REPORT_TYPE, TEXT_REGDATE, PROCESSING_STATUS, BOARD_TYPE 
 FROM (SELECT ROW_NUMBER() OVER(ORDER BY SEQ DESC) RN,
   SEQ, EMAIL, REPORT_TYPE, TEXT_REGDATE, PROCESSING_STATUS, BOARD_TYPE
   FROM REPORTBOARD r)
  WHERE RN BETWEEN 1 AND 10;
  

SELECT SEQ, EMAIL, REPORT_TYPE, CONTENT, TEXT_REGDATE, PROCESSING_STATUS, BOARD_TYPE 
 FROM REPORTBOARD r 
  WHERE SEQ = '4';
  

INSERT INTO REPORTBOARD
(SEQ, EMAIL, REPORT_TYPE, CONTENT, TEXT_REGDATE, PROCESSING_STATUS, BOARD_TYPE)
VALUES(REPORTBOARD_SEQ.NEXTVAL, 'katie32@naver.com', '욕설/비방', '심한 욕설을 하여 신고합니다.', SYSDATE, 'N' , '동행찾기 게시판');
