CREATE TABLE "MEMBER"  (
	 EMAIL 	VARCHAR2(50)	NOT NULL PRIMARY KEY,
	 PASSWORD 	VARCHAR2(20) NOT NULL,
	 WITHDRAWAL 	CHAR(1)	 DEFAULT 'Y'NOT NULL,
	 JOINDATE 	DATE	NOT NULL,
	 NICKNAME 	VARCHAR2(30)	NOT NULL,
	 AUTH 	CHAR(1)		DEFAULT 'U' NOT NULL
);

-- 댓글 게시판 --

CREATE TABLE  COMMENTBOARD  (
	 COMM_SEQ 	NUMBER	NOT NULL,
	 ONEDAY_SEQ 	VARCHAR2(50)	NOT NULL,
	 EMAIL 	VARCHAR2(50)	NOT NULL,
	 REFFER 	NUMBER	NOT NULL,
	 DEPTH 	NUMBER	NOT NULL,
	 STEP 	NUMBER	NOT NULL,
	 REGDATE 	DATE	NOT NULL,
	 CONTENT 	VARCHAR2(500)	NOT NULL,
	 REPORTCHK 	CHAR(1) DEFAULT 'N' NOT NULL
);


-- 댓글 입력 -- 
INSERT INTO COMMENTBOARD(
	COMM_SEQ,ONEDAY_SEQ,
	EMAIL,REFFER,DEPTH,
	STEP,REGDATE,CONTENT)
	VALUES (SEQ_COMM.NEXTVAL,2,
	'A002',(SELECT NVL(MAX(REFFER),0) FROM COMMENTBOARD)+1,0,0,SYSDATE,'같이가욥');

-- 댓글 시퀀스 -- 
CREATE SEQUENCE SEQ_COMM START WITH 1
INCREMENT BY 1;

-- 답글 입력 --


-- 업데이트 먼저 --
UPDATE COMMENTBOARD SET STEP = STEP +1
	WHERE STEP > (SELECT STEP FROM COMMENTBOARD WHERE COMM_SEQ=2)
	AND REFFER = (SELECT REFFER FROM COMMENTBOARD WHERE COMM_SEQ=2);

-- 답글 작성 -- 
INSERT INTO COMMENTBOARD(
    COMM_SEQ,ONEDAY_SEQ,EMAIL,
    REFFER,DEPTH,
    STEP,REGDATE,CONTENT)
	VALUES(SEQ_COMM.NEXTVAL,2,'A004',
	(SELECT REFFER FROM COMMENTBOARD WHERE COMM_SEQ=2),(SELECT DEPTH FROM COMMENTBOARD WHERE COMM_SEQ = 2)+1,
	(SELECT STEP FROM COMMENTBOARD WHERE COMM_SEQ = 2)+1,SYSDATE,'너무 바쁘다');


-- 리뷰 게시판 --
CREATE TABLE  REVIEWBOARD  (
	PLACE_SEQ 	NUMBER	NOT NULL,
	UUID_NAME 	VARCHAR2(1000)	NULL,
	ORIGIN_NAME 	VARCHAR2(1000)	NULL,
	IMG_URL 	VARCHAR2(1000)	NULL,
	CONTENT 	VARCHAR2(1200)	NULL
);

ALTER TABLE REVIEWBOARD
ADD CONSTRAINT FK_PLACE_SEQ FOREIGN KEY(PLACE_SEQ) REFERENCES PLACE(PLACE_SEQ);

-- 

