DROP TABLE "MEMBER" ;

CREATE TABLE "MEMBER"(
	EMAIL VARCHAR2(50) NOT NULL,
	NICKNAME VARCHAR2(30) NOT NULL,
	PASSWORD VARCHAR2(20),
	AUTH CHAR(1) NOT NULL,
	WITHDRAWAL CHAR(1) NOT NULL,
	JOINDATE DATE NOT NULL,
	CONSTRAINT "MEMBER_FK" CHECK ("AUTH" IN ('U','A')),
	CONSTRAINT "MEMBER_PK" PRIMARY KEY("EMAIL")
);


--회원가입을 하는 기능
INSERT INTO "MEMBER" 
(EMAIL,NICKNAME,PASSWORD,AUTH,WITHDRAWAL,JOINDATE)
VALUES('qr2277@naver.com','석규','tt001!','U','N',SYSDATE);

--API 회원가입 기능
INSERT INTO "MEMBER" 
(EMAIL, NICKNAME, AUTH, WITHDRAWAL, JOINDATE)
VALUES('josoekgyu@google.com','석규','U','N', SYSDATE);

--관리자 회원가입
INSERT INTO "MEMBER" 
(EMAIL, NICKNAME, PASSWORD, AUTH, WITHDRAWAL, JOINDATE)
VALUES('CarpeDiem@gmail.com','운영자','ADMIN01','A','N', SYSDATE);


--회원아이디중복체크 기능
SELECT COUNT(EMAIL) EMAIL
FROM MEMBER 
WHERE EMAIL = 'qr2277@naver.com';

--일반 회원 로그인 기능
SELECT EMAIL, NICKNAME, AUTH, JOINDATE
FROM MEMBER 
WHERE EMAIL = 'qr2277@naver.com'
AND PASSWORD = 'tt001!'
AND WITHDRAWAL = 'N';

--API 회원 로그인 기능
SELECT EMAIL,NICKNAME,AUTH,WITHDRAWAL
        FROM  MEMBER m 
        WHERE EMAIL ='josoekgyu@google.com'
        AND NICKNAME ='석규'
        AND WITHDRAWAL ='N';
       
--관리자 로그인 기능       
SELECT EMAIL, NICKNAME, PASSWORD AUTH, WITHDRAWAL , JOINDATE 
 FROM MEMBER m 
  WHERE EMAIL='CarpeDiem@gmail.com'
   AND PASSWORD ='ADMIN01'
   AND AUTH ='A';

--비밀번호 재설정 기능
UPDATE MEMBER SET PASSWORD ='tjrrb1111' 
WHERE EMAIL = 'qr2277@naver.com';


--회원탈퇴 기능
UPDATE MEMBER SET WITHDRAWAL ='Y'
WHERE EMAIL = 'qr2277@naver.com';

--전체 회원을 조회 하는 기능(페이징)
SELECT EMAIL,NICKNAME,AUTH,WITHDRAWAL,JOINDATE 
        FROM 
(SELECT EMAIL,NICKNAME,AUTH,WITHDRAWAL,JOINDATE, 
   ROW_NUMBER () OVER (ORDER BY JOINDATE DESC) ONE
        FROM MEMBER m)
WHERE ONE BETWEEN  1 AND 3 ; 