
DROP TABLE NOTE ;

DROP TABLE ONEDAY ;

DROP TABLE PLACE ;

DROP TABLE REVIEWBOARD ;

--NOTE 노트 테이블
CREATE TABLE NOTE(	
	NOTE_SEQ       NUMBER    PRIMARY KEY,
	EMAIL          VARCHAR2      (50),
	NOTE_DEL       CHAR      (1) DEFAULT 'N',
	NOTE_READCNT   NUMBER    ,
	NOTE_TITLE     VARCHAR2  (30) NOT NULL,
	NOTE_REGDATE   DATE
);

ALTER TABLE NOTE
ADD CONSTRAINT FK_EMAIL FOREIGN KEY(EMAIL) REFERENCES MEMBER(EMAIL);


--ONEDAY 하루 일정 테이블
CREATE TABLE ONEDAY(
	ONEDAY_SEQ NUMBER PRIMARY KEY,
	NOTE_SEQ NUMBER,
	ONEDAY_DELFLAG CHAR(1) DEFAULT 'N' NOT NULL,
	ONEDAY_TITLE VARCHAR2(30) NOT NULL,
	ONEDATE DATE NOT NULL,
	REPORTCHK     CHAR(1) DEFAULT 'N',
	ONE_READCNT   NUMBER,
	ONEDAY_PUBLIC CHAR(1) DEFAULT 'N'
);

ALTER TABLE ONEDAY
ADD CONSTRAINT FK_NOTE_SEQ FOREIGN KEY(NOTE_SEQ) REFERENCES NOTE(NOTE_SEQ);


-- PLACE 장소 테이블
CREATE TABLE PLACE (
	PLACE_SEQ NUMBER PRIMARY KEY,
	ONEDAY_SEQ NUMBER, --FK
	STEP NUMBER NOT NULL,
	PLACE_NAME VARCHAR2(50) NOT NULL,
	XLat DECIMAL(16,7) NOT NULL,
	YLNG DECIMAL(16,7) NOT NULL,
	MEMO VARCHAR2(4000)
);

ALTER TABLE PLACE 
ADD CONSTRAINT FK_ONEDAY_SEQ FOREIGN KEY(ONEDAY_SEQ) REFERENCES ONEDAY(ONEDAY_SEQ);

DROP SEQUENCE SEQ_NOTE;
DROP SEQUENCE SEQ_ONEDAY;
DROP SEQUENCE SEQ_PLACE;

CREATE SEQUENCE SEQ_NOTE START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_ONEDAY START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_PLACE START WITH 1
INCREMENT BY 1;