SELECT n.NOTE_SEQ, n.NOTE_TITLE , n.EMAIL, o.ONEDAY_TITLE, o.ONEDAY_SEQ , o.ONEDATE, o.ONEDAY_DELFLAG 
FROM NOTE n JOIN ONEDAY o
ON n.NOTE_SEQ = o.NOTE_SEQ
WHERE n.NOTE_SEQ = 99 AND o.ONEDAY_DELFLAG = 'N';


SELECT o.NOTE_SEQ , o.ONEDAY_SEQ , o.ONEDAY_TITLE, o.ONEDATE,
p.PLACE_SEQ, p.STEP, p.PLACE_NAME, p.XLAT, p.YLNG, p.MEMO
FROM ONEDAY o JOIN PLACE p
ON o.ONEDAY_SEQ = p.ONEDAY_SEQ
WHERE o.NOTE_SEQ = 99
ORDER BY STEP ASC;


-- 해당 노트(note_seq)의 모든 하루일정의/ 모든 장소 조회 하는법
